### ISSUE TITLE
Old version of PySimpleGUI

### ISSUE THREAD

**Issue by PySimpleGUI** [kianweelee/Edator#1]
Hiya.... saw a datascience Reddit post that led me here and quickly spotted that your'e running PySimpleGUI.

I see you're running version 4.8.0 of PySimpleGUI.  That release is "old" in the life of the project, about 6 months old.  A lot has changed since then.  The newest version is 4.19.0.  Any particular reason you've stuck with an older (and thus unsupported) release?  Or have you been keeping up to date and it is simply not reflected in your screenshot and readme file?

**Comment by kianweelee** [comment]
Oh I have written this Readme long time ago. Will update the version accordingly! Thanks for letting me know!
